#!/usr/bin/env bash
set -e
version="${1?Error: \$version not set.}"

rm -rf PFERD dist
git clone --depth 1 -c advice.detachedHead=false --branch $version https://github.com/Garmelon/PFERD.git -q
cd PFERD

python -m build
twine check dist/*

mv dist ../dist
