[workspace]
name = "pferd-pypi"
channels = ["conda-forge"]
exclude-newer = "7d"
platforms = ["osx-arm64", "linux-64"]

[tasks]
build = "./build v3.9.0"

[dependencies]
"python-build" = "*"
"twine" = "*"
